export const unknownNft = {
  image: '',
  symbol: 'ukn',
  id: 'unknown',
  name: 'unknown',
}

export const unknownToken = {
  image: '',
  symbol: 'ukn',
  id: 'unknown',
  name: 'unknown',
}

// Static NFT collection metadata
export const staticNFTs = [
  {
    name: "KAYC",
    symbol: "KAYC",
    module: "free.KAYC",
    image: "",
  },
]

export const staticTokens = [
  {
    name: "ARKD",
    symbol: "ARKD",
    coingeckoId: "",
    module: "arkade.token",
    icon: "/tokens/arkd.svg",
  },
  {
    module: "coin",
    symbol: "KDA",
    coingeckoId: "kadena",
    name: "Kadena",
    icon: "/tokens/kadena.svg",
  },
  
  {
    symbol: "BKA",
    coingeckoId: "",
    name: "Backalley",
    module: "free.backalley",
    icon: "/tokens/backalley.png",
  },
  {
    name: "CRNA",
    symbol: "CRNA",
    coingeckoId: "",
    module: "free.corona-token",
    icon: "/tokens/crna.png",
  },
  {
    name: "CRKK",
    symbol: "CRKK",
    coingeckoId: "",
    module: "free.crankk01",
    icon: "/tokens/crankk.png",
  },
  {
    name: "CFLY",
    symbol: "CFLY",
    coingeckoId: "",
    module: "free.cyberfly_token",
    icon: "/tokens/cfly.png",
  },
  
  {
    name: "Finux",
    symbol: "FINUX",
    coingeckoId: "",
    module: "free.finux",
    icon: "/tokens/finux.svg",
  },
  {
    symbol: "JDE",
    name: "Jodie",
    coingeckoId: "",
    module: "free.jodie-token",
    icon: "/tokens/jodie.png",
  },
  {
    name: "Babena",
    symbol: "BABE",
    coingeckoId: "",
    module: "free.babena",
    icon: "/tokens/babe.svg",
  },
  {
    name: "Kapy",
    symbol: "KAPY",
    coingeckoId: "",
    module: "free.kapybara-token",
    icon: "/tokens/kapy.png",
  },
  {
    name: "Purple Kdoge",
    symbol: "KDOGE",
    coingeckoId: "",
    module: "free.kdoge",
    icon: "/tokens/kdoge.png",
  },
  {
    symbol: "KISHK",
    coingeckoId: "",
    name: "Kishu Ken",
    module: "free.kishu-ken",
    icon: "/tokens/kishk.png",
  },
  {
    name: "MAGA",
    symbol: "MAGA",
    coingeckoId: "",
    module: "free.maga",
    icon: "/tokens/maga.png",
  },
  {
    name: "Teckel",
    symbol: "TECKEL",
    coingeckoId: "",
    module: "free.teckel",
    icon: "/tokens/teckel.png",
  },
  {
    name: "Hype",
    symbol: "HYPE",
    coingeckoId: "",
    module: "hypercent.prod-hype-coin",
    icon: "/tokens/hypercent.svg",
  },
  {
    id: "kaddex",
    symbol: "KDX",
    name: "Kaddex",
    coingeckoId: "",
    module: "kaddex.kdx",
    icon: "/tokens/kaddex.svg",
  },
  {
    id: "kdswap",
    symbol: "KDS",
    name: "KDSwap",
    coingeckoId: "",
    module: "kdlaunch.kdswap-token",
    icon: "/tokens/kdswap.svg",
  },
  {
    id: "kdlaunch",
    symbol: "KDL",
    name: "KDLaunch",
    coingeckoId: "",
    module: "kdlaunch.token",
    icon: "/tokens/kdl.svg",
  },
  {
    name: "Mok",
    symbol: "MOK",
    coingeckoId: "",
    module: "mok.token",
    icon: "/tokens/mok.png",
  },
  {
    name: "BRO",
    symbol: "BRO",
    coingeckoId: "",
    module: "n_582fed11af00dc626812cd7890bb88e72067f28c.bro",
    icon: "/tokens/bro.png",
  },
  {
    name: "zUSD",
    symbol: "zUSD",
    coingeckoId: "",
    module: "n_b742b4e9c600892af545afb408326e82a6c0c6ed.zUSD",
    icon: "/tokens/zusd.svg",
  },
  {
    name: "HERON",
    symbol: "HERON",
    coingeckoId: "",
    module: "n_e309f0fa7cf3a13f93a8da5325cdad32790d2070.heron",
    icon: "/tokens/heron.png",
  },
  {
    name: "Flux",
    symbol: "FLUX",
    coingeckoId: "",
    module: "runonflux.flux",
    icon: "/tokens/flux.svg",
  },
  {
    name: "Wizards Arena",
    symbol: "WIZA",
    coingeckoId: "",
    module: "free.wiza",
    icon: "/tokens/wiza.png",
  },
  {
    name: "UNITT",
    symbol: "UNITT",
    coingeckoId: "",
    module: "n_ebe54249b2e9d68f5060961f3c419f828d18dc2.unitt",
    icon: "/tokens/unitt.svg",
  },
  {
    name: "Kadena Wrapped USDC",
    symbol: "kwUSDC",
    coingeckoId: "",
    module: "lago.kwUSDC",
    icon: "/tokens/kwusdc.svg",
  },
  {
    name: "Azuki",
    symbol: "AZUKI",
    coingeckoId: "",
    module: "n_581defa50d2abe95cdecb8956eb9772383ee274a9.AZUKI",
    icon: "/tokens/azuki.png",
  },
  {
    name: "Kapepe",
    symbol: "KPP",
    coingeckoId: "",
    module: "n_5a7ccd559b245b7dcbd5259e1ee43d04fbf93eab.kapepe",
    icon: "/tokens/kapepe.png",
  },
  {
    name: "Ktoshi",
    symbol: "KTOSHI",
    coingeckoId: "",
    module: "n_625e9938aee84bdb7d190f14fc283c7a6dfc15d58.ktoshi",
    icon: "/tokens/ktoshi.png",
  }
]
