export const unknownNft = {
  image: '',
  symbol: 'ukn',
  id: 'unknown',
  name: 'unknown',
}

export const unknownToken = {
  image: '',
  symbol: 'ukn',
  id: 'unknown',
  name: 'unknown',
}

export const staticTokens = [
  {
    name: "ARKD",
    symbol: "ARKD",
    coingeckoId: "",
    module: "arkade.token",
    icon: "",
  },
  {
    module: "coin",
    symbol: "KDA",
    coingeckoId: "kadena",
    name: "Kadena",
    icon: "/tokens/kadena.svg",
  },
  {
    name: "KAYC",
    symbol: "KAYC",
    coingeckoId: "",
    module: "free.KAYC",
    icon: "",
  },
  {
    symbol: "BKA",
    coingeckoId: "",
    name: "Backalley",
    module: "free.backalley",
    icon: "",
  },
  {
    name: "CRNA",
    symbol: "CRNA",
    coingeckoId: "",
    module: "free.corona-token",
    icon: "",
  },
  {
    name: "CRKK",
    symbol: "CRKK",
    coingeckoId: "",
    module: "free.crankk01",
    icon: "/tokens/crankk.png",
  },
  {
    name: "CFLY",
    symbol: "CFLY",
    coingeckoId: "",
    module: "free.cyberfly_token",
    icon: "",
  },
  {
    name: "DOC",
    symbol: "DOC",
    coingeckoId: "",
    module: "free.docu",
    icon: "",
  },
  {
    name: "FINUX",
    symbol: "FINUX",
    coingeckoId: "",
    module: "free.finux",
    icon: "",
  },
  {
    symbol: "JDE",
    name: "Jodie",
    coingeckoId: "",
    module: "free.jodie-token",
    icon: "",
  },
  {
    name: "Kapy",
    symbol: "KAPY",
    coingeckoId: "",
    module: "free.kapybara-token",
    icon: "",
  },
  {
    id: "kishu-ken",
    symbol: "KISHK",
    coingeckoId: "",
    name: "Kishu Ken",
    module: "free.kishu-ken",
    icon: "/tokens/kishu.svg",
  },
  {
    name: "MAGA",
    symbol: "MAGA",
    coingeckoId: "",
    module: "free.maga",
    icon: "",
  },
  {
    name: "Hype",
    symbol: "HYPE",
    coingeckoId: "",
    module: "hypercent.prod-hype-coin",
    icon: "/tokens/hypercent.svg",
  },
  {
    id: "kaddex",
    symbol: "KDX",
    name: "Kaddex",
    coingeckoId: "",
    module: "kaddex.kdx",
    icon: "/tokens/kaddex.svg",
  },
  {
    id: "kdswap",
    symbol: "KDS",
    name: "KDSwap",
    coingeckoId: "",
    module: "kdlaunch.kdswap-token",
    icon: "",
  },
  {
    id: "kdlaunch",
    symbol: "KDL",
    name: "KDLaunch",
    coingeckoId: "",
    module: "kdlaunch.token",
    icon: "/tokens/launch.svg",
  },
  {
    name: "Mok",
    symbol: "MOK",
    coingeckoId: "",
    module: "mok.token",
    icon: "",
  },
  {
    name: "BRO",
    symbol: "BRO",
    coingeckoId: "",
    module: "n_582fed11af00dc626812cd7890bb88e72067f28c.bro",
    icon: "",
  },
  {
    name: "zUSD",
    symbol: "zUSD",
    coingeckoId: "",
    module: "n_b742b4e9c600892af545afb408326e82a6c0c6ed.zUSD",
    icon: "",
  },
  {
    name: "HERON",
    symbol: "HERON",
    coingeckoId: "",
    module: "n_e309f0fa7cf3a13f93a8da5325cdad32790d2070.heron",
    icon: "",
  },
  {
    name: "Flux",
    symbol: "FLUX",
    coingeckoId: "",
    module: "runonflux.flux",
    icon: "",
  }
]
